module.exports = {
    express : require('express'),
    mongoose : require('mongoose'),
    passport : require('passport'),
    morgan : require('morgan'),
    flash : require('connect-flash'),
    fs : require('fs'),
    path : require('path'),
    cookieParser : require('cookie-parser'),
    bodyParser : require('body-parser'),
    session : require('express-session'),
    url : require('url'),
    monk : require('monk'),
    nodemailer : require('nodemailer'),
    bcrypt : require('bcrypt'),
}